# Server configuration for Federated Learning with ADNI

# Use the same data configuration as clients for consistency
# (though server typically doesn't load data)
data:
  train_csv_path: "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
  val_csv_path: "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"
  img_dir: "data/ADNI/3T_bl_org_P1_20250603/3T_bl_org_MRI_1_NIfTI_removedDup_step3_skull_stripping"
  dataset_type: "normal"
  classification_mode: "CN_AD"
  mci_subtype_filter: ["LMCI", "AD"]
  resize_size: [96, 96, 73]
  resize_mode: "trilinear"
  use_spacing: false
  spacing_size: [1.0, 1.0, 1.0]
  transform_device: "cuda"
  multiprocessing_context: "spawn"

model:
  name: "rosanna_cnn"
  num_classes: 2
  pretrained_checkpoint: null
  # Pretrained model specific parameters
  freeze_encoder: false  # Set to true for feature extraction only
  dropout: 0.1  # Dropout rate for regularization
  input_channels: 1  # Number of input channels

training:
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.01
  seed: 244
  num_workers: 2
  num_epochs: 2
  output_dir: "outputs"  # Checkpoints will be saved in {output_dir}/checkpoints/
  checkpoint:
    save_frequency: 10

# Federated Learning specific settings
fl:
  num_rounds: 100              # Number of FL rounds to perform
  fraction_fit: 1.0            # Fraction of clients to sample in each round for training
  fraction_evaluate: 1.0       # Fraction of clients to sample for evaluation
  min_fit_clients: 3           # Minimum number of clients for training
  min_evaluate_clients: 3      # Minimum number of clients for evaluation
  min_available_clients: 3     # Minimum number of total clients
  local_epochs: 2              # Default number of local epochs (can be overridden by client configs)
  strategy: "fedavg"           # FL aggregation strategy (options: "fedavg", "fedprox")
  evaluate_frequency: 5       # Clients will evaluate every 10 rounds instead of every round

  # Multi-machine configuration for distributed FL
  multi_machine:
    # Server machine configuration
    server:
      host: "otter21.eps.surrey.ac.uk"
      username: "th01167"
      password: null  # Will use FL_PASSWORD environment variable
      port: 9092
      config_file: "configs/fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg/fl_server.yaml"
      sequential_experiment: true
      train_sequential_labels:
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
        - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_train_847images.csv"
      val_sequential_labels:
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"
        # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"
        - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_all_val_188images.csv"

    # Client machines configuration
    clients:
      - host: "otter50.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 0
        project_dir: null  # Will use global project_dir
        config_file: "configs/fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg/client1.yaml"
        sequential_experiment: true
        train_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_train_282images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_train_282images.csv"
        val_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_val_63images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_1_val_63images.csv"
      - host: "otter66.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 1
        project_dir: null  # Will use global project_dir
        config_file: "configs/fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg/client2.yaml"
        sequential_experiment: true
        train_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_train_283images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_train_283images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_train_283images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_train_283images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_train_283images.csv"
        val_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_val_63images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_val_63images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_2_val_63images.csv"
      - host: "otter27.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 2
        project_dir: null  # Will use global project_dir
        config_file: "configs/fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg/client3.yaml"
        sequential_experiment: true
        train_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_train_282images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_train_282images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_train_282images.csv"
        val_sequential_labels:
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed01/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_val_62images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed10/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_val_62images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed42/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_val_62images.csv"
          # - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed101/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_val_62images.csv"
          - "data/ADNI/LABELS/3T_bl_org_trainval_1035images_3clients_seed244/3T_bl_org_MRI_UniqueSID_trainval_1035images_fullmetadata_client_3_val_62images.csv"

    # Project configuration
    project_dir: "/user/HS402/th01167/Surrey/fl-adni-classification"
    venv_path: "/user/HS402/th01167/.venv/master/bin/python"
    venv_activate: "/user/HS402/th01167/.venv/master/bin/activate"

    # SSH configuration
    ssh:
      timeout: 30
      banner_timeout: 30
      auth_timeout: 30

# Wandb logging configuration
wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["federated-learning", "fedavg", "rosanna"]
  notes: "fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg-seed244"
  run_name: "fl-rosanna-3T_P1-trainval_1035images-2classes-3clients-fedavg-seed244"
