# Server configuration for Federated Learning with ADNI

# Use the same data configuration as clients for consistency
# (though server typically doesn't load data)
data:
  train_csv_path: "data/ADNI/LABELS/3T_bl_org_1220images_3clients/3T_bl_org_MRI_UniqueSID_1220images_client_all_train_853images.csv"
  val_csv_path: "data/ADNI/LABELS/3T_bl_org_1220images_3clients/3T_bl_org_MRI_UniqueSID_1220images_client_all_val_181images.csv"
  img_dir: "data/ADNI/3T_bl_org_P1_20250603/3T_bl_org_MRI_1_NIfTI_removedDup_step3_skull_stripping"
  dataset_type: "normal"
  classification_mode: "CN_AD"
  mci_subtype_filter: ["LMCI", "AD"]
  resize_size: [182, 218, 182]
  resize_mode: "trilinear"
  use_spacing: false
  spacing_size: [1.0, 1.0, 1.0]
  transform_device: "cpu"
  multiprocessing_context: "fork"

model:
  name: "securefed_cnn"
  num_classes: 2
  pretrained_checkpoint: null

training:
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.01
  seed: 42
  num_workers: 4
  num_epochs: 2
  output_dir: "outputs"  # Checkpoints will be saved in {output_dir}/checkpoints/
  checkpoint:
    save_frequency: 10

# Federated Learning specific settings
fl:
  num_rounds: 200              # Number of FL rounds to perform
  fraction_fit: 1.0            # Fraction of clients to sample in each round for training
  fraction_evaluate: 1.0       # Fraction of clients to sample for evaluation
  min_fit_clients: 3           # Minimum number of clients for training
  min_evaluate_clients: 3      # Minimum number of clients for evaluation
  min_available_clients: 3     # Minimum number of total clients
  local_epochs: 2              # Default number of local epochs (can be overridden by client configs)
  strategy: "fedprox"           # FL aggregation strategy (options: "fedavg", "fedprox")
  evaluate_frequency: 5       # Clients will evaluate every 10 rounds instead of every round
  fedprox_mu: 0.1  # FedProx regularization parameter

# Wandb logging configuration
wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["federated-learning", "securefed-cnn", "fedprox"]
  notes: "fl-securefed-fedprox-3clients-1220images-2classes-LMCI-fixed_aug-mu0.1"
  run_name: "fl-securefed-3T_P1-1220images-2classes-3clients-fedprox-mu0.1"
