# Server configuration for Federated Learning with ADNI

# Use the same data configuration as clients for consistency
# (though server typically doesn't load data)
data:
  train_csv_path: "data/ADNI/LABELS/3T_bl_org_1220images_3clients/3T_bl_org_MRI_UniqueSID_1220images_client_all_train_853images.csv"
  val_csv_path: "data/ADNI/LABELS/3T_bl_org_1220images_3clients/3T_bl_org_MRI_UniqueSID_1220images_client_all_val_181images.csv"
  img_dir: "data/ADNI/3T_bl_org_P1_20250603/3T_bl_org_MRI_1_NIfTI_removedDup_step3_skull_stripping"
  dataset_type: "normal"
  classification_mode: "CN_AD"
  mci_subtype_filter: ["LMCI", "AD"]
  resize_size: [96, 96, 73]
  resize_mode: "trilinear"
  use_spacing: false
  spacing_size: [1.0, 1.0, 1.0]
  transform_device: "cuda"
  multiprocessing_context: "spawn"

model:
  name: "rosanna_cnn"
  num_classes: 2
  pretrained_checkpoint: null
  # Pretrained model specific parameters
  freeze_encoder: false  # Set to true for feature extraction only
  dropout: 0.1  # Dropout rate for regularization
  input_channels: 1  # Number of input channels

training:
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.01
  seed: 42
  num_workers: 8
  num_epochs: 2
  output_dir: "outputs"  # Checkpoints will be saved in {output_dir}/checkpoints/
  checkpoint:
    save_frequency: 10

# Federated Learning specific settings
fl:
  num_rounds: 100              # Number of FL rounds to perform
  fraction_fit: 1.0            # Fraction of clients to sample in each round for training
  fraction_evaluate: 1.0       # Fraction of clients to sample for evaluation
  min_fit_clients: 2           # Minimum number of clients for training
  min_evaluate_clients: 2      # Minimum number of clients for evaluation
  min_available_clients: 2     # Minimum number of total clients
  local_epochs: 2              # Default number of local epochs (can be overridden by client configs)
  strategy: "fedavg"           # FL aggregation strategy (options: "fedavg", "fedprox")
  evaluate_frequency: 5       # Clients will evaluate every 10 rounds instead of every round

  # FedProx-specific parameters
  fedprox_mu: 0.1             # Proximal term coefficient (controls client regularization strength)

  # Multi-machine configuration for distributed FL
  multi_machine:
    # Server machine configuration
    server:
      host: "otter81.eps.surrey.ac.uk"
      username: "th01167"
      password: null  # Will use FL_PASSWORD environment variable
      port: 9092

    # Client machines configuration
    clients:
      - host: "otter82.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 0
        project_dir: null  # Will use global project_dir
      - host: "otter83.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 1
        project_dir: null  # Will use global project_dir
      - host: "otter84.eps.surrey.ac.uk"
        username: "th01167"
        password: null  # Will use FL_PASSWORD environment variable
        partition_id: 2
        project_dir: null  # Will use global project_dir

    # Project configuration
    project_dir: "/user/HS402/th01167/Surrey/fl-adni-classification"
    venv_path: "/user/HS402/th01167/.venv/master/bin/python"
    venv_activate: "/user/HS402/th01167/.venv/master/bin/activate"

    # SSH configuration
    ssh:
      timeout: 30
      banner_timeout: 30
      auth_timeout: 60

# Wandb logging configuration
wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["federated-learning", "fedavg", "rosanna"]
  notes: "fl-rosanna-3T_P1-1220images-2classes-3clients-fedavg"
  run_name: "fl-rosanna-3T_P1-1220images-2classes-3clients-fedavg"
