data:
  train_csv_path: "data/ADNI/ADNI1_Complete_1Yr_3T/ADNI1_Complete_1Yr_3T_4_06_2025.csv"
  val_csv_path: "data/ADNI/ADNI1_Complete_1Yr_3T/ADNI1_Complete_1Yr_3T_codetest.csv"
  img_dir: "data/ADNI/ADNI1_Complete_1Yr_3T/ADNI"
  resize_size: [160, 160, 160]  # Default resize dimensions (height, width, depth)
  resize_mode: "trilinear"  # Default resize mode

model:
  name: "resnet3d"  # Options: "resnet3d", "densenet3d"
  num_classes: 3  # AD, MCI, CN
  model_depth: 50  # For ResNet3D
  pretrained: false
  weights_path: null

training:
  batch_size: 2
  num_epochs: 100
  learning_rate: 0.0001  # Reduced learning rate for stability
  weight_decay: 0.01  # Increased weight decay for regularization
  num_workers: 4
  output_dir: "/scratch/th01167/fl-adni/checkpoints/resnet"

wandb:
  use_wandb: false  # Set to true to enable Weights & Biases tracking
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: []  # Add tags to categorize your runs
  notes: null  # Add notes to describe your experiment 
  run_name: "default"  # Add run name to describe your experiment 