data:
  train_csv_path: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_594images_client_all_train_475images.csv"
  val_csv_path: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_594images_client_all_val_119images.csv"
  img_dir: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_611images"
  resize_size: [128, 128, 128]  # Reduced from [224, 224, 224]
  resize_mode: "trilinear"
  use_spacing: true  # Enable spacing transform
  spacing_size: [1.5, 1.5, 1.5]  # Target spacing in mm
  target: "DX"  # Target column for classification (DX or Group)

model:
  name: "resnet3d"
  num_classes: 3  # CN, MCI, AD
  model_depth: 18  # Using ResNet-18 instead of ResNet-50
  pretrained_checkpoint: null

training:
  batch_size: 4
  num_epochs: 300
  learning_rate: 0.0001
  weight_decay: 0.01
  num_workers: 4
  output_dir: "/scratch/th01167/fl-adni/checkpoints/resnet"
  gradient_accumulation_steps: 2
  mixed_precision: true
  visualize: false
  lr_scheduler: "cosine"
  checkpoint:
    save_best: true
    save_latest: true
    save_regular: false
    save_frequency: 10

wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["low-memory", "random-split"]
  notes: "ResNet3D-18 with reduced memory usage for small dataset"
  run_name: "resnet18_low_memory"
