# Data configuration
data:
  train_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  val_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  img_dir: "data/ADNI/codetest"
  resize_size: [160, 160, 160]  # Default resize dimensions (height, width, depth)
  resize_mode: "trilinear"  # Default resize mode

# Model configuration
model:
  name: "densenet3d"
  num_classes: 3  # AD, MCI, CN
  growth_rate: 32
  block_config: [6, 12, 24, 16]
  pretrained_checkpoint: null

# Training configuration
training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  num_workers: 4
  output_dir: "/scratch/th01167/fl-adni/checkpoints/densenet"
  visualize: false
  lr_scheduler: "plateau"
  checkpoint:
    save_best: true
    save_latest: true
    save_regular: false
    save_frequency: 10

# Weights & Biases configuration
wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["densenet"]
  notes: "DenseNet3D model for ADNI classification"
  run_name: "densenet-codetest"
