data:
  train_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  val_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  img_dir: "data/ADNI/codetest"
  resize_size: [160, 160, 160]
  resize_mode: "trilinear"

model:
  name: "resnet3d"
  num_classes: 3
  model_depth: 18
  pretrained_checkpoint: null

training:
  batch_size: 2
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  num_workers: 4
  output_dir: "/scratch/th01167/fl-adni/checkpoints/resnet"
  gradient_accumulation_steps: 1
  mixed_precision: false
  visualize: false
  lr_scheduler: "plateau"
  checkpoint:
    save_best: true
    save_latest: true
    save_regular: false
    save_frequency: 10

wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["resnet18"]  # Add tags to categorize your runs
  notes: "Using ResNet3D-18 for small dataset"  # Add notes to describe your experiment
  run_name: "resnet18-codetest"  # Add run name to describe your experiment
