# Data configuration
data:
  train_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  val_csv_path: "data/ADNI/codetest/ADNI1_Complete_1Yr_3T_codetest.csv"
  img_dir: "data/ADNI/codetest"
  resize_size: [160, 160, 160]  # Default resize dimensions (height, width, depth)
  resize_mode: "trilinear"  # Default resize mode

# Model configuration
model:
  name: "resnet3d"
  num_classes: 3
  pretrained: false
  weights_path: null

# Training configuration
training:
  batch_size: 4
  num_workers: 4
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  output_dir: "/scratch/th01167/fl-adni/checkpoints/resnet"

# Weights & Biases configuration
wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["resnet"]
  notes: "ResNet3D model for ADNI classification"
  run_name: "resnet-codetest"
