data:
  train_csv_path: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_594images_client_all_train_475images.csv"
  val_csv_path: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_594images_client_all_val_119images.csv"
  img_dir: "data/ADNI/ALL_1.5T_bl_ScaledProcessed_MRI_611images_step3_skull_stripping"
  resize_size: [182, 218, 182]  # Default resize dimensions (height, width, depth)
  resize_mode: "trilinear"  # Default resize mode
  use_spacing: false  # Disable spacing transform since images are already preprocessed
  spacing_size: [1.0, 1.0, 1.0]  # Original spacing in mm (not used when use_spacing is false)
  cache_rate: 1.0  # Cache 100% of data in memory for faster training
  cache_num_workers: 10  # Workers for creating the cache (separate from DataLoader workers)

model:
  name: "securefed_cnn"  # Using our secure federated CNN model
  num_classes: 3  # CN, MCI, AD
  pretrained_checkpoint: null

training:
  batch_size: 10
  num_epochs: 300
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_workers: 10
  output_dir: "/scratch/th01167/fl-adni/checkpoints/securefed_cnn"
  mixed_precision: false
  visualize: false
  lr_scheduler: "plateau"
  val_epoch_freq: 10
  use_class_weights: true
  class_weight_type: "inverse"
  # Optional: manual_class_weights: [1.0, 2.0, 3.0]  # For manual weighting
  checkpoint:
    save_best: true
    save_latest: true
    save_regular: false
    save_frequency: 10

wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["securefed-cnn", "1.5T_bl_scaled_594images_skullstripped"]
  notes: "Using the SecureFedCNN model for ADNI classification"
  run_name: "securefed-cnn-training-1.5T_bl_scaled_594images_skullstripped"
