data:
  train_csv_path: "data/ADNI/3T_bl_org_MRI_UniqueSID_1220images_client_all_train_853images.csv"
  val_csv_path: "data/ADNI/3T_bl_org_MRI_UniqueSID_1220images_client_all_val_182images.csv"
  img_dir: "data/ADNI/3T_bl_org_P1_20250603/3T_bl_org_MRI_1_NIfTI_removedDup_step3_skull_stripping"
  dataset_type: "normal"  # Options: "smartcache", "cache", "normal"
  classification_mode: "CN_AD"  # Options: "CN_MCI_AD" (3 classes), "CN_AD" (2 classes, where MCI is treated as CN)
  mci_subtype_filter: ["LMCI", "AD"]  # Optional: Filter MCI samples by subtypes. Can be single subtype or list. Valid: "SMC", "EMCI", "LMCI". Use null to include all MCI samples.
  resize_size: [182, 218, 182]  # Default resize dimensions (height, width, depth)
  resize_mode: "trilinear"  # Default resize mode
  use_spacing: false  # Disable spacing transform since images are already preprocessed
  spacing_size: [1.0, 1.0, 1.0]  # Original spacing in mm (not used when use_spacing is false)
  cache_rate: 0.5  # Cache 100% of data in memory for faster training
  cache_num_workers: 8  # Workers for creating the cache (separate from DataLoader workers)
  transform_device: "cuda"  # Device to use for transforms (e.g., "cuda" or "cpu")
  multiprocessing_context: "spawn"  # Options: "spawn", "fork", "forkserver"

model:
  name: "securefed_cnn"  # Using our secure federated CNN model
  num_classes: 2  # CN, MCI, AD - will be automatically adjusted based on classification_mode
  pretrained_checkpoint: null

training:
  batch_size: 4
  num_epochs: 500
  learning_rate: 0.0001
  weight_decay: 0.01
  num_workers: 4
  seed: 42
  output_dir: "outputs_centralized"
  mixed_precision: false
  visualize: false
  lr_scheduler: "plateau"
  val_epoch_freq: 10
  use_class_weights: false
  class_weight_type: "inverse"
  # Optional: manual_class_weights: [1.0, 2.0, 3.0]  # For manual weighting
  loss_type: "focal"  # Options: "cross_entropy", "focal"
  focal_alpha: 0.75   # Alpha parameter for Focal Loss (typically 0.25-1.0)
                      # Set to null to use class_weights as alpha instead
  focal_gamma: 2.0    # Gamma parameter for Focal Loss (typically 0.5-5.0)
                      # Higher values focus more on hard examples
  checkpoint:
    save_best: true
    save_latest: true
    save_regular: false
    save_frequency: 10

wandb:
  use_wandb: true
  project: "fl-adni-classification"
  entity: "tin-hoang"
  tags: ["securefed-cnn", "3T_P1-1220images-2classes", "focal_loss"]
  notes: "data_aug_moderate_LMCI"
  run_name: "securefed-3T_P1-1220images-2classes-LMCI-focal"
